version: '3.8'

services:
  rag-api:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    command: uvicorn api:app --host 0.0.0.0 --port 8001
    # command: python api.py     # For running the API 